export const items = [
  {
    id: 1,
    category: 'mobiles',
    title: "Apple iPhone 16",
    imgSrc: 'https://m.media-amazon.com/images/I/71CSc3M2AGL._SX679_.jpg',
    amazonLink: 'https://www.amazon.in/iPhone-16-128-GB-Control/dp/B0DGJH8RYG',
    description: 'Apple iPhone 16 (128 GB) - Teal',
    price: '89999',
  },
  {
    id: 2,
    category: 'mobiles',
    title: "Apple iPhone 11",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/44MiYi6',
    description: 'Apple iPhone 11 (64GB) - White',
    price: '79999',
  },
  {
    id: 3,
    category: 'mobiles',
    title: "Apple iPhone 13",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3r6XJtv',
    description: 'Apple iPhone 13 (128GB) - Blue',
    price: '69999',
  },
  {
    id: 4,
    category: 'laptops',
    title: "Lenovo IdeaPad Slim 5",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/44JsK4r',
    description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm)',
    price: '29999',
  },
  {
    id: 5,
    category: 'laptops',
    title: "Xiaomi [Smartchoice] Notebookpro",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3EzeQaC',
    description: 'Xiaomi [Smartchoice] Notebookpro',
    price: '49999',
  },
  {
    id: 6,
    category: 'tablets',
    title: "Lenovo Tab P12 Pro AMOLED",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonLink: 'https://amzn.to/3RabsdH',
    description: 'Lenovo Tab P12 Pro AMOLED (12.6", 8 GB, 256 GB, Wi-fi Only)',
    price: '19999',
  },
  {
    id: 7,
    category: 'tablets',
    title: "Xiaomi Pad 6",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonLink: 'https://amzn.to/3ZeNRdY',
    description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870',
    price: '29999',
  },
  {
    id: 8,
    category: 'laptops',
    title: "Apple MacBook Air Laptop",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3r9rvhm',
    description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch Retina Display',
    price: '89999',
  },
  {
    id: 9,
    category: 'tablets',
    title: "Samsung Galaxy Tab A8",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonLink: 'https://amzn.to/3Pdsh4F',
    description: 'Samsung Galaxy Tab A8 10.5" Display, 4GB RAM, 64GB Storage',
    price: '49999',
  },
  {
    id: 10,
    category: 'mobiles',
    title: "Samsung Galaxy S23 Ultra",
    imgSrc: 'https://m.media-amazon.com/images/I/61VfL-aiToL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3Rl1Zjx',
    description: 'Samsung Galaxy S23 Ultra 5G (12GB, 256GB)',
    price: '124999',
  },
  {
    id: 11,
    category: 'mobiles',
    title: "OnePlus 11R 5G",
    imgSrc: 'https://m.media-amazon.com/images/I/61amb0CfMGL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3T0nKlB',
    description: 'OnePlus 11R 5G (8GB RAM, 128GB Storage)',
    price: '39999',
  },
  {
    id: 12,
    category: 'laptops',
    title: "ASUS ROG Zephyrus G14",
    imgSrc: 'https://m.media-amazon.com/images/I/91zVSkGGZbS._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3T2kzvK',
    description: 'ASUS ROG Zephyrus G14 Gaming Laptop',
    price: '129999',
  },
  {
    id: 13,
    category: 'tablets',
    title: "Apple iPad Air (5th Gen)",
    imgSrc: 'https://m.media-amazon.com/images/I/61XZQXFQeVL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3T4kk34',
    description: 'Apple iPad Air (5th Gen, Wi-Fi, 64GB) - Blue',
    price: '54999',
  },
  {
    id: 14,
    category: 'mobiles',
    title: "iQOO Z7 5G",
    imgSrc: 'https://m.media-amazon.com/images/I/61VbKHdE0rL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3VvztLy',
    description: 'iQOO Z7 5G by vivo (6GB RAM, 128GB ROM)',
    price: '15499',
  },
  {
    id: 15,
    category: 'laptops',
    title: "Samsung Galaxy Book3",
    imgSrc: 'https://m.media-amazon.com/images/I/71vFKBpKakL._SL1500_.jpg',
    amazonLink: 'https://amzn.to/3VvvUM3',
    description: 'Samsung Galaxy Book3 (Intel Core i5 13th Gen)',
    price: '65999',
  }
];


